version: "3.9"
services:
  db:
    image: postgres:13
    user: "${UID}:${UID}"
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: $DB_PASSWORD
  app:
    build: 
      context: .
      args:
        UID: "${UID}"
    user: "${UID}:${UID}"
    env_file: .env
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/cloud-operation-slack-bot
    ports:
      - "3000:3000"
    depends_on:
      - db