apiVersion: v1
kind: Secret
metadata:
  name: cloudopsbot-app-secrets
type: Opaque
stringData:
  rails_secret_key_base: {{ .Values.rails.secret_key_base }}
  slack_signing_secret: {{ .Values.slack.signing_secret }}
  slack_oauth_token: {{ .Values.slack.oauth_token }}
  snow_basic_auth_username: {{ .Values.snow.basic_auth_username }}
  snow_basic_auth_password: {{ .Values.snow.basic_auth_password }}