on:
  issues:
    types:
      - opened

name: Jira Issue Creation Demo
jobs:
  jiraIssueCreation:
    name: Jira Issue Creation Demo
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Jira Creation Demo
        uses: bryannice/gitactions-jira-issue-creation@master
        env:
          JIRA_ACCOUNT_URL: https://dsdmoj.atlassian.net/
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN_AR }}
          JIRA_ISSUE_DESCRIPTION: Demo Jira Issue Creation
          JIRA_ISSUE_SUMMARY: Demo Jira Issue Creation
          JIRA_ISSUE_TYPE: Story
          JIRA_PROJECT: PTTP
          JIRA_USERNAME: aaron.robinson1@justice.gov.uk
